const icons={search:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7"></circle><path d="m16 16 4 4"></path></svg>',heart:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.5 1.1-1.1a5.5 5.5 0 0 0-.1-7.8Z"></path></svg>',menu:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"></path></svg>',close:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"></path></svg>',home:'<svg viewBox="0 0 24 24"><path d="m4 11 8-7 8 7v9H4z"></path></svg>',grid:'<svg viewBox="0 0 24 24"><path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z"></path></svg>',book:'<svg viewBox="0 0 24 24"><path d="M4 5a3 3 0 0 1 3-3h5v18H7a3 3 0 0 0-3 3zM20 5a3 3 0 0 0-3-3h-5v18h5a3 3 0 0 1 3 3z"></path></svg>',list:'<svg viewBox="0 0 24 24"><path d="M8 6h12M8 12h12M8 18h12M4 6h.01M4 12h.01M4 18h.01"></path></svg>'};
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icons[el.dataset.icon]||'');
const page=document.body.dataset.page;document.querySelectorAll('.main-nav a').forEach(a=>{if(a.dataset.page===page)a.setAttribute('aria-current','page')});
const storeKey='kagefuda-watch-v2';let watched=JSON.parse(localStorage.getItem(storeKey)||'[]');const countEls=document.querySelectorAll('[data-watch-count]');
function paintWatch(){countEls.forEach(el=>el.textContent=watched.length);document.querySelectorAll('[data-watch]').forEach(btn=>{const on=watched.includes(btn.dataset.watch);btn.classList.toggle('active',on);btn.setAttribute('aria-pressed',String(on));btn.title=on?'ウォッチから削除':'ウォッチに追加'})}
function toast(message){const el=document.querySelector('#toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),3200)}
document.addEventListener('click',e=>{const w=e.target.closest('[data-watch]');if(w){e.preventDefault();e.stopPropagation();const id=w.dataset.watch;watched=watched.includes(id)?watched.filter(x=>x!==id):[...watched,id];localStorage.setItem(storeKey,JSON.stringify(watched));paintWatch();toast(watched.includes(id)?`LOT ${id} をウォッチしました`:`LOT ${id} をウォッチから外しました`)}const bid=e.target.closest('[data-bid]');if(bid){e.preventDefault();bid.disabled=true;bid.textContent='照合中…';setTimeout(()=>{bid.disabled=false;bid.textContent='入札を確認';toast('入札資格を照合しました。身元記録が一致しません。')},900)}});paintWatch();
const modal=document.querySelector('#search-modal');document.querySelectorAll('[data-open-search]').forEach(b=>b.addEventListener('click',()=>{modal?.classList.add('open');modal?.querySelector('input')?.focus()}));document.querySelectorAll('[data-close-search]').forEach(b=>b.addEventListener('click',()=>modal?.classList.remove('open')));modal?.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});document.addEventListener('keydown',e=>{if(e.key==='Escape')modal?.classList.remove('open')});
const search=document.querySelector('[data-catalog-search]'),category=document.querySelector('[data-category]'),empty=document.querySelector('.empty-state');function filterCatalog(){if(!search)return;const q=search.value.trim().toLowerCase(),cat=category?.value||'all';let shown=0;document.querySelectorAll('[data-lot-card]').forEach(card=>{const ok=(!q||card.dataset.search.includes(q))&&(cat==='all'||card.dataset.category===cat);card.style.display=ok?'block':'none';if(ok)shown++});if(empty)empty.style.display=shown?'none':'block';const n=document.querySelector('[data-result-count]');if(n)n.textContent=shown}search?.addEventListener('input',filterCatalog);category?.addEventListener('change',filterCatalog);filterCatalog();
const revealObs='IntersectionObserver'in window?new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');revealObs.unobserve(e.target)}}),{threshold:.08}):null;document.querySelectorAll('.reveal').forEach(el=>revealObs?revealObs.observe(el):el.classList.add('visible'));
document.querySelectorAll('[data-countdown]').forEach((el,i)=>{let seconds=1046+i*1682;setInterval(()=>{seconds=Math.max(0,seconds-1);const h=String(Math.floor(seconds/3600)).padStart(2,'0'),m=String(Math.floor(seconds%3600/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');el.textContent=`${h}:${m}:${s}`},1000)});
document.documentElement.classList.add('js-loaded');document.body.insertAdjacentHTML('afterbegin','<div class="page-wipe" aria-hidden="true"></div>');
const mobileNav=`<nav class="mobile-dock" aria-label="モバイルナビ"><a href="index.html" class="${page==='home'?'active':''}">${icons.home}<span>ホーム</span></a><a href="auctions.html" class="${page==='auctions'?'active':''}">${icons.grid}<span>競売</span></a><a href="archive.html" class="${page==='archive'?'active':''}">${icons.book}<span>来歴</span></a><button type="button" data-mobile-more>${icons.menu}<span>その他</span></button></nav><div class="mobile-sheet" data-mobile-sheet><div class="mobile-sheet-panel"><div class="kicker">Kagefuda directory</div><div class="mobile-sheet-links"><a href="private-sale.html">Private Sale</a><a href="about.html">影札について</a><a href="account.html">会員デスク</a></div><div class="mobile-sheet-meta">SESSION KFA-07-10-N<br>VIEWER 0130</div></div></div>`;document.body.insertAdjacentHTML('beforeend',mobileNav);const sheet=document.querySelector('[data-mobile-sheet]');document.querySelector('[data-mobile-more]')?.addEventListener('click',()=>sheet.classList.toggle('open'));sheet?.addEventListener('click',e=>{if(e.target===sheet)sheet.classList.remove('open')});
const catalogTop=document.querySelector('.catalog-top');if(catalogTop){catalogTop.insertAdjacentHTML('beforeend',`<div class="catalog-view" aria-label="表示形式"><button class="view-btn active" data-view="grid" aria-label="グリッド表示">${icons.grid}</button><button class="view-btn" data-view="list" aria-label="リスト表示">${icons.list}</button></div>`)}document.querySelectorAll('[data-view]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelector('.catalog-grid')?.classList.toggle('list-view',btn.dataset.view==='list')}));
document.querySelectorAll('[data-hero-search]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const q=form.querySelector('input').value.trim();location.href='auctions.html'+(q?`?q=${encodeURIComponent(q)}`:'')}));if(search){const q=new URLSearchParams(location.search).get('q');if(q){search.value=q;filterCatalog()}}

// Standalone pages can return to the local archive terminal. Inside the
// simulated browser the desktop chrome already provides this affordance.
if(window.top===window.self&&!document.body.classList.contains('observer-page')){
  const terminalLink=document.createElement('a');
  terminalLink.className='desktop-return';
  terminalLink.href='desktop.html';
  terminalLink.setAttribute('aria-label','仮想デスクトップへ戻る');
  terminalLink.innerHTML='<span aria-hidden="true">KFA</span><b>仮想端末を開く</b><small>ARCHIVE-07</small>';
  document.body.appendChild(terminalLink);
}
