(()=>{
const KEY='kagefuda-observer-v1',now=Date.now(),page=document.body.dataset.page||location.pathname.split('/').pop()||'home';
const pageNames={home:'正面目録',auctions:'開催中競売',archive:'来歴保管庫',about:'鑑定基準',account:'会員照合',private:'非公開取引',observer:'観測記録',secret:'LOT 0000'};
const hash=s=>[...s].reduce((a,c)=>(a*31+c.charCodeAt(0))>>>0,2166136261);
let state;try{state=JSON.parse(localStorage.getItem(KEY)||'null')}catch{state=null}if(!state){const seed=Math.random().toString(36).slice(2,8).toUpperCase();state={id:`KFA-13-${seed}`,firstSeen:now,visits:{},actions:[],searches:[],solved:false,unlocked:false}}
state.visits[page]=(state.visits[page]||0)+1;state.actions.unshift({at:now,type:'visit',value:pageNames[page]||page});state.actions=state.actions.slice(0,30);
const watched=()=>{try{return JSON.parse(localStorage.getItem('kagefuda-watch-v2')||'[]')}catch{return[]}};
const metrics=()=>{const distinct=Object.keys(state.visits).filter(x=>x!=='observer'&&x!=='secret').length,watches=watched().length,searches=[...new Set(state.searches)].length;return{distinct,watches,searches,score:Math.min(13,distinct*2+watches*2+searches+(state.solved?4:0))}};
const persist=()=>{const m=metrics();state.unlocked=state.solved&&m.score>=8;localStorage.setItem(KEY,JSON.stringify(state));return m};persist();
const record=(type,value)=>{state.actions.unshift({at:Date.now(),type,value});state.actions=state.actions.slice(0,30);persist();paintBeacon()};
document.querySelectorAll('[data-watch]').forEach(el=>el.addEventListener('click',()=>setTimeout(()=>record('watch',el.dataset.watch),0)));
document.querySelectorAll('[data-hero-search]').forEach(f=>f.addEventListener('submit',()=>{const q=f.querySelector('input')?.value.trim();if(q){state.searches.push(q);record('search',q)}}));
document.querySelector('[data-catalog-search]')?.addEventListener('change',e=>{const q=e.target.value.trim();if(q){state.searches.push(q);record('search',q)}});
function paintBeacon(){if(page==='observer'||page==='secret')return;let beacon=document.querySelector('.observer-beacon');if(!beacon){beacon=document.createElement('a');beacon.href='observer.html';beacon.className='observer-beacon';document.body.appendChild(beacon)}const m=metrics();beacon.classList.toggle('unlocked',state.unlocked);beacon.innerHTML=`<i></i><span>観測同期 <b>${m.score}/13</b>${state.unlocked?' · 新規ロット':''}</span>`}
paintBeacon();
const roles=['境界の保管者','返却記録の証人','第十三観測者','欠番目録の入札者'],verbs=['まだ到着していない品を待っている','過去から閲覧されている','四度目のベルを聞いている','自分の落札履歴を先に残した'];const h=hash(state.id),persona=`あなたは「${roles[h%roles.length]}」。記録によれば、${verbs[(h>>>3)%verbs.length]}。`;
window.KagefudaObserver={state,metrics,persist,record,persona,hash};
if(page==='observer')renderObserver();if(page==='secret')renderSecret();
function renderObserver(){const m=metrics();document.querySelectorAll('[data-observer-id]').forEach(e=>e.textContent=state.id);document.querySelector('[data-persona]').textContent=persona;document.querySelector('[data-score]').innerHTML=`${m.score}<small> / 13</small>`;document.querySelector('[data-progress]').style.width=`${m.score/13*100}%`;const steps=[['複数の目録を閲覧',m.distinct>=2,`${m.distinct}/2`],['ロットを一件以上選別',m.watches>=1,`${m.watches}/1`],['照合語を復元',state.solved,state.solved?'完了':'未完了']];document.querySelector('[data-steps]').innerHTML=steps.map((s,i)=>`<div class="protocol-step ${s[1]?'done':''}"><div class="protocol-step-index">${String(i+1).padStart(2,'0')}</div><strong>${s[0]}</strong><span>${s[2]}</span></div>`).join('');const logText={visit:'閲覧',watch:'選別',search:'検索',solve:'照合'};document.querySelector('[data-log]').innerHTML=state.actions.map(a=>`<div class="log-row"><time>${new Date(a.at).toLocaleTimeString('ja-JP',{hour12:false})}</time><p>${logText[a.type]||a.type} / ${escapeHtml(String(a.value))}</p></div>`).join('');drawMap();const form=document.querySelector('[data-protocol-form]');form.addEventListener('submit',e=>{e.preventDefault();const value=form.querySelector('input').value.replace(/\D/g,'');const msg=document.querySelector('[data-protocol-message]');if(value==='0317'){state.solved=true;record('solve','03:17');msg.textContent='照合しました。あなたの記録は、初回閲覧より前に作成されています。';renderObserver()}else{msg.textContent='不一致。三つの独立した記録が停止した時刻を確認してください。'}});document.querySelector('[data-secret-gate]').classList.toggle('open',state.unlocked)}
function drawMap(){const svg=document.querySelector('[data-evidence-map]'),nodes=[['HOME',70,75,'home'],['LOTS',220,55,'auctions'],['0417',370,100,'auctions'],['11/31',330,230,'archive'],['PRIVATE',150,245,'private'],['YOU',220,155,'observer']];let lines='';for(let i=0;i<nodes.length-1;i++)lines+=`<line x1="${nodes[i][1]}" y1="${nodes[i][2]}" x2="220" y2="155"/>`;svg.innerHTML=`${lines}${nodes.map(n=>`<circle class="${state.visits[n[3]]?'active':''}" cx="${n[1]}" cy="${n[2]}" r="${n[0]==='YOU'?10:7}"/><text x="${n[1]+12}" y="${n[2]+3}">${n[0]}</text>`).join('')}`}
function renderSecret(){if(!state.unlocked){location.replace('observer.html');return}document.querySelectorAll('[data-observer-id]').forEach(e=>e.textContent=state.id);document.querySelector('[data-persona]').textContent=persona;document.querySelector('[data-first-seen]').textContent=new Date(state.firstSeen).toLocaleString('ja-JP');document.querySelector('[data-visit-count]').textContent=Object.values(state.visits).reduce((a,b)=>a+b,0);document.querySelector('[data-accept-secret]')?.addEventListener('click',e=>{e.currentTarget.textContent='引継ぎ記録を作成しました';record('accept','LOT 0000');document.querySelector('[data-secret-response]').textContent='受取場所：あなたが最初にこのページを開いた部屋。到着予定：11月31日 03:17。'})}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
})();
